# ######JSON######
PREPROCESS = 'preprocess'
PATH_LIST = 'path_list'
OUTPUT_PATH = 'output_path'
AMR = 'amr'
AMRS = 'amrs'
JMAR_ROOT_PATH = 'jamr_root_path'
LOG_PATH = 'log_path'
CLASSIFICATION = 'classification'
MATRIX_PATH = 'matrix_path'
TARGETS_PATH = 'targets_path'
DATASET = 'dataset'
SPLITTED_DOCUMENTS_PATH = 'splitted_documents'
MATRIX = 'matrix'
NAME = 'name'
PROCESS_TYPE = 'process_type'
IN_FILE = 'in_file'
FILE_LIST = 'file_list'

